# GNU Make project makefile autogenerated by GENie
ifndef config
  config=debug32
endif

ifndef verbose
  SILENT = @
endif

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

ifeq (posix,$(SHELLTYPE))
  MKDIR = $(SILENT) mkdir -p "$(1)"
  COPY  = $(SILENT) cp -fR "$(1)" "$(2)"
else
  MKDIR = $(SILENT) mkdir "$(subst /,\\,$(1))" 2> nul || true
  COPY  = $(SILENT) copy /Y "$(subst /,\\,$(1))" "$(subst /,\\,$(2))"
endif

CC  = $(MINGW)/bin/x86_64-w64-mingw32-gcc
CXX = $(MINGW)/bin/x86_64-w64-mingw32-g++
AR  = $(MINGW)/bin/ar

ifndef RESCOMP
  ifdef WINDRES
    RESCOMP = $(WINDRES)
  else
    RESCOMP = windres
  endif
endif

ifeq ($(config),debug32)
  OBJDIR     = ../../_build/win32_mingw-gcc/obj/x32/Debug/cmft_cli
  TARGETDIR  = ../../_build/win32_mingw-gcc/bin
  TARGET     = $(TARGETDIR)/cmftDebug
  DEFINES   += -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -DWIN32
  INCLUDES  += -I../../dependency/bx/include/compat/mingw -I../../dependency -I../../src/cmft -I../../src -I../../include
  ALL_CPPFLAGS  += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS    += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -m32 -std=c++11 -Wunused-value -fdata-sections -ffunction-sections -msse2 -Wundef -m32
  ALL_CXXFLAGS  += $(CXXFLAGS) $(ALL_CFLAGS) -fno-rtti -fno-exceptions
  ALL_RESFLAGS  += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS   += $(LDFLAGS) -L../../dependency/lib/win32_mingw-gcc -L$(DXSDK_DIR)/lib/x86 -m32 -L/usr/lib32 -Wl,--gc-sections -static-libgcc -static-libstdc++
  LDDEPS    +=
  LIBS      += $(LDDEPS)
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release32)
  OBJDIR     = ../../_build/win32_mingw-gcc/obj/x32/Release/cmft_cli
  TARGETDIR  = ../../_build/win32_mingw-gcc/bin
  TARGET     = $(TARGETDIR)/cmftRelease
  DEFINES   += -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -DWIN32
  INCLUDES  += -I../../dependency/bx/include/compat/mingw -I../../dependency -I../../src/cmft -I../../src -I../../include
  ALL_CPPFLAGS  += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS    += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -O3 -m32 -std=c++11 -Wunused-value -fdata-sections -ffunction-sections -msse2 -Wundef -m32
  ALL_CXXFLAGS  += $(CXXFLAGS) $(ALL_CFLAGS) -fno-rtti -fno-exceptions
  ALL_RESFLAGS  += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS   += $(LDFLAGS) -L../../dependency/lib/win32_mingw-gcc -L$(DXSDK_DIR)/lib/x86 -m32 -L/usr/lib32 -Wl,--gc-sections -static-libgcc -static-libstdc++
  LDDEPS    +=
  LIBS      += $(LDDEPS)
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug64)
  OBJDIR     = ../../_build/win64_mingw-gcc/obj/x64/Debug/cmft_cli
  TARGETDIR  = ../../_build/win64_mingw-gcc/bin
  TARGET     = $(TARGETDIR)/cmftDebug
  DEFINES   += -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -DWIN32
  INCLUDES  += -I../../dependency/bx/include/compat/mingw -I../../dependency -I../../src/cmft -I../../src -I../../include
  ALL_CPPFLAGS  += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS    += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -m64 -std=c++11 -Wunused-value -fdata-sections -ffunction-sections -msse2 -Wundef -m64
  ALL_CXXFLAGS  += $(CXXFLAGS) $(ALL_CFLAGS) -fno-rtti -fno-exceptions
  ALL_RESFLAGS  += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS   += $(LDFLAGS) -L../../dependency/lib/win64_mingw-gcc -L$(DXSDK_DIR)/lib/x64 -L$(GLES_X64_DIR) -m64 -L/usr/lib64 -Wl,--gc-sections -static-libgcc -static-libstdc++
  LDDEPS    +=
  LIBS      += $(LDDEPS)
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release64)
  OBJDIR     = ../../_build/win64_mingw-gcc/obj/x64/Release/cmft_cli
  TARGETDIR  = ../../_build/win64_mingw-gcc/bin
  TARGET     = $(TARGETDIR)/cmftRelease
  DEFINES   += -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -DWIN32
  INCLUDES  += -I../../dependency/bx/include/compat/mingw -I../../dependency -I../../src/cmft -I../../src -I../../include
  ALL_CPPFLAGS  += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS    += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -O3 -m64 -std=c++11 -Wunused-value -fdata-sections -ffunction-sections -msse2 -Wundef -m64
  ALL_CXXFLAGS  += $(CXXFLAGS) $(ALL_CFLAGS) -fno-rtti -fno-exceptions
  ALL_RESFLAGS  += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS   += $(LDFLAGS) -L../../dependency/lib/win64_mingw-gcc -L$(DXSDK_DIR)/lib/x64 -L$(GLES_X64_DIR) -m64 -L/usr/lib64 -Wl,--gc-sections -static-libgcc -static-libstdc++
  LDDEPS    +=
  LIBS      += $(LDDEPS)
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/src/cmft/clcontext.o \
	$(OBJDIR)/src/cmft/image.o \
	$(OBJDIR)/src/cmft/allocator.o \
	$(OBJDIR)/src/cmft/cubemapfilter.o \
	$(OBJDIR)/src/cmft/common/print.o \
	$(OBJDIR)/src/cmft/common/stb_image.o \
	$(OBJDIR)/src/main.o \

OBJDIRS := \
	$(OBJDIR) \
	$(OBJDIR)/src \
	$(OBJDIR)/src/cmft/common \
	$(OBJDIR)/src/cmft \

RESOURCES := \

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIRS) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking cmft_cli
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
	-$(call MKDIR,$(TARGETDIR))

$(OBJDIRS):
	@echo Creating $(OBJDIR)
	-$(call MKDIR,$(OBJDIR))
	-$(call MKDIR,$(OBJDIR)/src)
	-$(call MKDIR,$(OBJDIR)/src/cmft/common)
	-$(call MKDIR,$(OBJDIR)/src/cmft)

clean:
	@echo Cleaning cmft_cli
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -MMD -MP $(DEFINES) $(INCLUDES) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
endif

$(OBJDIR)/src/cmft/clcontext.o: ../../src/cmft/clcontext.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/src/cmft/image.o: ../../src/cmft/image.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/src/cmft/allocator.o: ../../src/cmft/allocator.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/src/cmft/cubemapfilter.o: ../../src/cmft/cubemapfilter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/src/cmft/common/print.o: ../../src/cmft/common/print.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/src/cmft/common/stb_image.o: ../../src/cmft/common/stb_image.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/src/main.o: ../../src/main.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(OBJDIR)/$(notdir $(PCH)).d
endif
